nelmio_cors:
  defaults:
  paths:
    "^/":
      origin_regex: true
      allow_origin: ["^https://albionsite-frontend.herokuapp.com"]
      allow_headers: ["X-Custom-Auth"]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
      max_age: 3600
